# Generated by Django 4.1.2 on 2022-11-01 16:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_location_description_alter_location_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='reporter',
        ),
        migrations.AlterField(
            model_name='location',
            name='reported_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
