# Generated by Django 4.1.2 on 2022-12-01 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_location_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
